/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calendar;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tom13
 */
public class Calendar extends javax.swing.JFrame {
    //先設定好最上面的星期
    String[] colname = {
        "星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"
    };
    Object[][] data = {};
    public static int year = 0, weekDay = 0;
    public DefaultTableModel myModel = null;

    public Calendar() {
        initComponents();
        myModel = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtyear = new javax.swing.JTextField();
        btn減 = new javax.swing.JButton();
        btn加 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            data,
            colname
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        jLabel1.setText("年分:");

        txtyear.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });

        btn減.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        btn減.setText("減");
        btn減.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn減ActionPerformed(evt);
            }
        });

        btn加.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        btn加.setText("加");
        btn加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn加ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn減)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn加)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btn減, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btn加, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //主要程式段
    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        //從輸入框取得文字，並將其轉為int
        year = Integer.parseInt(txtyear.getText());
        Object[] day = new Object[7];
        Object[] mon = new Object[7];
        Object[] space = new Object[7];
        //呼叫函式找出當年的第一天
        int n = firstWeekDayOfYear(year);
        for (int i = 1; i <= 12; i++) {
            mon[0] = i + " 月";
            myModel.addRow(mon);
            for (int j = 0; j < 7; j++) {
                day[j] = " ";
            }
            //呼叫函式取得當月有幾天
            for (int j = 1; j <= getMonthOfDays(i, year); j++) {
                day[n] = j;
                n++;
                if (n == 7) {
                    myModel.addRow(day);
                    n = 0;
                }
                if (j == getMonthOfDays(i, year) && n < 7) {
                    for (int k = n; k < 7; k++) {
                        day[k] = " ";
                    }
                    myModel.addRow(day);
                }
            }
            myModel.addRow(space);
        }
    }//GEN-LAST:event_txtyearActionPerformed

    //增加年份並重新顯示
    private void btn加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn加ActionPerformed
        year = year + 1;
        txtyear.setText(String.valueOf(year));
        myModel.setRowCount(0);
        txtyearActionPerformed(evt);
    }//GEN-LAST:event_btn加ActionPerformed

    //減少年份並重新顯示
    private void btn減ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn減ActionPerformed
        year = year - 1;
        txtyear.setText(String.valueOf(year));
        myModel.setRowCount(0);
        txtyearActionPerformed(evt);
    }//GEN-LAST:event_btn減ActionPerformed

    //檢查是否為閏年
    public static boolean isLeapYear(int year) {
        return ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0));
    }

    //找出當年的第一天
    public static int firstWeekDayOfYear(int year) {
        long day = year * 365;
        for (int i = 1; i < year; i++) {
            if (isLeapYear(i)) {
                day += 1;
            }
        }
        return (int) day % 7;
    }
    
    //回傳當月有幾天
    public static int getMonthOfDays(int month, int year) {
        switch (month) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                return 31;
            case 4:
            case 6:
            case 9:
            case 11:
                return 30;
            case 2:
                if (isLeapYear(year)) {
                    return 29;
                } else {
                    return 28;
                }
            default:
                return 0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calendar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn加;
    private javax.swing.JButton btn減;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
